### ISSUE TITLE
Upgrade Required

### ISSUE THREAD

**Issue by josjaf** [Akkadius/glass-isc-dhcp#47]
Hi 
Here is my compose file, I searched other issues, but I have 3000 open and there's nothing listening only on 8085
```
  isc-dhcp:
    container_name: dhcp
    image: "networkboot/dhcpd"
    network_mode: host
    volumes:
    - /opt/docker/dhcp/:/data/
  glass:
    container_name: glass
    image: "node:8"
    working_dir: /home/node/app
    security_opt:
        - apparmor:unconfined
    environment:
      - NODE_ENV=production
    volumes:
      - /opt/docker/glass/glass-isc-dhcp:/home/node/app
      - /opt/docker/dhcp/:/var/lib/dhcp
      - /opt/docker/dhcp/dhcpd.conf:/etc/dhcp/dhcpd.conf
      #- /srv/dhcp/
    ports:
      - "8085:8080"
      - "3005:3000"
    command: "/bin/sh -c 'npm install && npm start'"
```
